


message(STATUS "")
message(STATUS "================== HMP Summary =====================")
message(STATUS     "  Main Project            : ${_HMP_MAIN_PROJECT}")
message(STATUS     "  CMAKE_SYSTEM_NAME       : ${CMAKE_SYSTEM_NAME}")
message(STATUS     "  CMAKE_CXX_COMPIER       : ${CMAKE_CXX_COMPILER_ID}")
message(STATUS     "  HMP_BUILD_VERSION       : ${HMP_BUILD_VERSION}")
message(STATUS "Dependences:")
message(STATUS     "  CUDA_ENABLED            : ${HMP_ENABLE_CUDA}")
if(HMP_ENABLE_CUDA)
    message(STATUS "    CUDA version          : ${CUDA_VERSION}")
    message(STATUS "    CUDA root directory   : ${CUDA_TOOLKIT_ROOT_DIR}")
    message(STATUS "    CUDA include path     : ${CUDA_INCLUDE_DIRS}")
    message(STATUS "    CUDA Arch Flags       : ${CUDA_ARCH_FLAGS}")
endif()
message(STATUS     "  FFMPEG_ENABLED          : ${HMP_ENABLE_FFMPEG}")
if(HMP_ENABLE_FFMPEG)
    message(STATUS "    FFMPEG ROOT           : ${FFMPEG_ROOT}")
    message(STATUS "    FFMPEG include path   : ${FFMPEG_INCLUDE_DIR}")
endif()
message(STATUS     "  OPENCV_ENABLED          : ${HMP_ENABLE_OPENCV}")
if(HMP_ENABLE_OPENCV)
    message(STATUS "    OPENCV include path   : ${OpenCV_INCLUDE_DIRS}")
    message(STATUS "    OPENCV Libraries      : ${OpenCV_LIBS}")
endif()
message(STATUS     "  NPP_ENABLED             : ${HMP_ENABLE_NPP}")
message(STATUS     "  OPENMP_ENABLED          : ${HMP_ENABLE_OPENMP}")
if(HMP_ENABLE_OPENMP)
    message(STATUS "     OpenMP_CXX_FLAGS     : ${OpenMP_CXX_FLAGS}")
    message(STATUS "     OpenMP_C_FLAGS       : ${OpenMP_C_FLAGS}")
endif()
message(STATUS     "  PYTHON ENABLED          : ${HMP_ENABLE_PYTHON}")
if(HMP_ENABLE_PYTHON)
    message(STATUS "      PYTHON VERSION      : ${Python_VERSION}, ${PYTHON_MODULE_EXTENSION}")
endif()
message(STATUS     "  TORCH ENABLED           : ${HMP_ENABLE_TORCH}")
if(HMP_ENABLE_TORCH)
    message(STATUS "      Version             : ${Torch_VERSION}")
endif()
message(STATUS     "  JNI ENABLED             : ${HMP_ENABLE_JNI}")
if(HMP_ENABLE_JNI)
    message(STATUS     "      JNI Libraries   : ${JNI_LIBRARIES}")
endif()
message(STATUS     "  MOBILE ENABLED          : ${HMP_ENABLE_MOBILE}")
