
message(STATUS "")
message(STATUS "================== BMF Summary =====================")
message(STATUS     "  CMAKE_SYSTEM_NAME       : ${CMAKE_SYSTEM_NAME}")
message(STATUS     "  CMAKE_CXX_COMPIER       : ${CMAKE_CXX_COMPILER_ID}")
message(STATUS     "  BMF_BUILD_VERSION       : ${BMF_VERSION_MAJOR}.${BMF_VERSION_MINOR}.${BMF_VERSION_PATCH}")
message(STATUS     "  BMF_BUILD_COMMIT        : ${BMF_BUILD_COMMIT}")
message(STATUS "Dependences:")
message(STATUS     "  CUDA_ENABLED            : ${BMF_ENABLE_CUDA}")
if(BMF_ENABLE_CUDA)
    message(STATUS "    CUDA version          : ${CUDA_VERSION}")
    message(STATUS "    CUDA root directory   : ${CUDA_TOOLKIT_ROOT_DIR}")
    message(STATUS "    CUDA include path     : ${CUDA_INCLUDE_DIRS}")
    message(STATUS "    CUDA Arch Flags       : ${CUDA_ARCH_FLAGS}")
endif()
message(STATUS     "  GLOG_ENABLED            : ${BMF_ENABLE_GLOG}")
message(STATUS     "  JNI_ENABLED             : ${BMF_ENABLE_JNI}")
message(STATUS     "  PYTHON_ENABLED          : ${BMF_ENABLE_PYTHON}")
if(BMF_ENABLE_PYTHON)
    message(STATUS "      PYTHON VERSION      : ${Python_VERSION}, ${PYTHON_MODULE_EXTENSION}")
endif()
message(STATUS     "  FFMPEG_ENABLED          : ${BMF_ENABLE_FFMPEG}")